services:
  ollama:
    image: ollama/ollama:latest
    ports:
        - 11434:11434
    volumes:
        - ./ollama/ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  car-claim-client:
    build:
      context: ./client
      no_cache: true
      dockerfile: Dockerfile
    image: car-claim-client:latest
    ports:
      - "8080:8080"
    restart: always
    container_name: car-claim-client
  car-claim-server:
    build:
      context: ./server
      no_cache: true
      dockerfile: Dockerfile
    command: ["node", "server.js"]
    image: car-claim-server:latest
    ports:
      - "9090:9090"
    restart: always
    container_name: car-claim-server
    environment:
      - MONGODB_ATLAS_URI=mongodb://user:pass@mongodb:27017/?directConnection=true
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      #- OLLAMA_BASE_URL=http://ollama:11434
      - LLM_MODEL=qwen2.5vl:7b
      - EMBEDDING_MODEL=mxbai-embed-large
      - OLLAMA_NUM_PARALLEL=6
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_NUM_THREAD=8
      - OLLAMA_GPU=true
      - OLLAMA_FLASH_ATTENTION=true
      - OLLAMA_KEEP_ALIVE=300s
      - DB_NAME=CarClaims
      - VEHICLE_DAMAGE_COLLECTION_NAME=vehicle_damage
      - UNHANDLED_CLAIMS_COLLECTION_NAME=unhandled_claims
      - PORT=9090

  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    container_name: mongodb-server
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017


volumes:
  ollama_data: {}
  open-webui: {}